### ISSUE TITLE
关于插件配置完，服务器启动日志输出机器人启动成功但是加入服务器没效果的issue

### ISSUE THREAD

**Issue by YGYoghurt** [Flandre923/kook-chat-fabric-dev#2]
关于插件配置完，服务器启动日志输出机器人启动成功但是加入服务器没效果的issue

**Comment by YGYoghurt** [comment]
我确认我的bot_token 与 channel_ID设置没问题，且kook上显示我的机器人上线但是进入服务器没效果

**Comment by YGYoghurt** [comment]
抱歉，我的问题，应该是要在子频道复制id

**Comment by Flandre923** [comment]
抱歉，昨天没时间，没看到。
